//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class OpexPaymentCOPPPhGet_Result
    {
        public Nullable<System.DateTime> PERIOD { get; set; }
        public string Jenis_pph_yang_dipotong { get; set; }
        public int Cara_pembayaran { get; set; }
        public string Nomor_bukti_potong { get; set; }
        public int Jenis_penghasilan { get; set; }
        public Nullable<decimal> object_pemotongan { get; set; }
        public Nullable<decimal> pph_yang_dipotong { get; set; }
        public Nullable<System.DateTime> tgl_bukti_potong { get; set; }
        public string npwp { get; set; }
        public string Nama_Pemotong { get; set; }
        public string Alamat_Pemotong { get; set; }
        public Nullable<int> iuran_pembayaran { get; set; }
        public Nullable<int> ntpn { get; set; }
        public Nullable<int> jumlah_pembayaran { get; set; }
        public Nullable<int> tgl_setor { get; set; }
    }
}
