//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ReportGetOpexPayment_Result
    {
        public string OPEX_PAYMENT_NO { get; set; }
        public string DOCUMENT_TYPE { get; set; }
        public string OPEX_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string BRANCH { get; set; }
        public string RECEPIENT_BANK_TYPE { get; set; }
        public string CCY { get; set; }
        public Nullable<decimal> BCA_IDR { get; set; }
        public Nullable<decimal> BTMU_IDR { get; set; }
        public Nullable<decimal> BTMU_USD { get; set; }
        public string BRANCH_GROUP { get; set; }
    }
}
