//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class TERORIS_SEARCH_Result
    {
        public Nullable<long> ROW { get; set; }
        public string BIRTHDAYS { get; set; }
        public string ADDRESS { get; set; }
        public string NATIONALITY { get; set; }
        public string OTHER_INFO { get; set; }
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string BIRTHPLACE { get; set; }
        public string DATEOFBIRTH { get; set; }
    }
}
