//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class HIGH_RISK_COUNTRY_GET_Result
    {
        public Nullable<long> NO { get; set; }
        public System.DateTime UPDATE_ON { get; set; }
        public int ID { get; set; }
        public string COUNTRY_NAME { get; set; }
    }
}
