//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ElearningDetailGet_Result
    {
        public Nullable<long> Number { get; set; }
        public string QuestionerCode { get; set; }
        public decimal QuestionerDtID { get; set; }
        public Nullable<int> QuestionerTypeID { get; set; }
        public string QuestionerTest { get; set; }
        public string QuestionerAnswer { get; set; }
        public Nullable<int> QuestionerScore { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Update_By { get; set; }
    }
}
