//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spHREmployeeDetailView_Result
    {
        public string JobEmployeeId { get; set; }
        public string NIK { get; set; }
        public string EmployeeName { get; set; }
        public int JobTypeId { get; set; }
        public string JobTypeName { get; set; }
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public string DepartementCode { get; set; }
        public string DepartementName { get; set; }
        public string PrivilegeCode { get; set; }
        public string PrivilegeName { get; set; }
        public System.DateTime EffectiveDateFrom { get; set; }
        public Nullable<System.DateTime> EffectiveDateTo { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public int JobStatus { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<int> BranchIdFrom { get; set; }
        public string BranchNameFrom { get; set; }
        public string DepartementCodeFrom { get; set; }
        public string DepartementNameFrom { get; set; }
        public string PrivilegeCodeFrom { get; set; }
        public string PrivilegeNameFrom { get; set; }
    }
}
