//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spGAPurchaseRequestDeliveryBarcodeView_Result
    {
        public int DeliveryBarcodeId { get; set; }
        public string DeliveryDetailId { get; set; }
        public string ItemBarcode { get; set; }
        public string AssetNo { get; set; }
        public string SerialNo { get; set; }
        public string ItemUser { get; set; }
    }
}
