//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ReportGetPWNominative_Result
    {
        public string Nominative_No { get; set; }
        public string Branch_Group { get; set; }
        public string BRANCH { get; set; }
        public Nullable<decimal> BCA_IDR { get; set; }
        public Nullable<decimal> BTMU_IDR { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
