//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spRptGAItemStockAssetDetail_Result
    {
        public Nullable<long> No { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemCategoryName { get; set; }
        public string ItemGroupName { get; set; }
        public string ItemTypeName { get; set; }
        public string ItemBarcode { get; set; }
        public string AssetNo { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string CodeName { get; set; }
        public string DepartementName { get; set; }
        public string BranchDepartement { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
