//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ElearningTestDetailGetAnswer_Result
    {
        public long QuestionerAnswerID { get; set; }
        public decimal QuestionerDtID { get; set; }
        public string Sequence { get; set; }
        public string QuestionerDtAnswer { get; set; }
        public int Score { get; set; }
    }
}
