//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ADMINFEE_GET_CONTRACT_Result
    {
        public Nullable<long> RowNumber { get; set; }
        public string Contract_Number { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Asset_cost_amount { get; set; }
        public int contract_term { get; set; }
        public Nullable<System.DateTime> commenceDate { get; set; }
        public Nullable<decimal> admin_fee { get; set; }
        public string contract_status_code { get; set; }
        public string PAID { get; set; }
        public string Input { get; set; }
    }
}
