//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spITActivityTaskList_Results
    {
        public string ActivityNo { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string ProblemTypeName { get; set; }
        public string ItemTypeCode { get; set; }
        public string BranchName { get; set; }
        public string RequestBy { get; set; }
        public string DepartementCode { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string PIC { get; set; }
        public string TerminatedBy { get; set; }
        public System.DateTime Created_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
