//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spHREmployeeView_Result
    {
        public string NIK { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string DepartementCode { get; set; }
        public string PrivilegeCode { get; set; }
        public bool IsResign { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public Nullable<System.DateTime> ResignEffectiveDate { get; set; }
        public bool IsActive { get; set; }
        public string BranchName { get; set; }
        public string DepartementName { get; set; }
        public string PrivilegeName { get; set; }
    }
}
