//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class OpexPaymentDetailCOPGetList_Result
    {
        public Nullable<long> Number { get; set; }
        public string OPEX_PAYMENT_NO { get; set; }
        public int OPEX_PAYMENT_IDX { get; set; }
        public string BRANCH_ALLOCATION { get; set; }
        public string SBP_ALLOCATION { get; set; }
        public string POLICY_NO { get; set; }
        public string NAME { get; set; }
        public string NIK { get; set; }
        public string PAYMENT_NO { get; set; }
        public decimal PREMI { get; set; }
        public decimal POLICY_FEE { get; set; }
        public decimal TOTAL_DEBIT { get; set; }
        public decimal COMISSION { get; set; }
        public decimal VAT { get; set; }
        public decimal WH_TAX { get; set; }
        public decimal TOTAL_CREDIT { get; set; }
        public decimal PAYMENT_TO_INSURANCE { get; set; }
        public string ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
    }
}
