//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spITMailReminderScheduleDetailView_Result
    {
        public int ScheduleId { get; set; }
        public int ReminderId { get; set; }
        public string MailTo { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string IntervalBy { get; set; }
        public Nullable<int> IntervalRange { get; set; }
        public string IntervalHour { get; set; }
        public string IntervalMinute { get; set; }
        public string Description { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_by { get; set; }
    }
}
