//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class NominativeGetHeader_Result
    {
        public string No { get; set; }
        public int Tahun { get; set; }
        public string resId { get; set; }
        public string ApplName { get; set; }
        public string CountpartyName { get; set; }
        public string Place { get; set; }
        public string DateTime { get; set; }
        public string Time { get; set; }
        public string EntertainmentType { get; set; }
        public Nullable<decimal> EstimatedBgt { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string EventItems { get; set; }
        public string APPLICATION_STATUS_CODE { get; set; }
        public Nullable<int> Branch { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> SBP { get; set; }
        public string SbpName { get; set; }
        public string ADDRESS { get; set; }
        public string BussinessLine { get; set; }
        public string Purpose { get; set; }
    }
}
