//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spBranchDomainView_Result
    {
        public string Branch_Code { get; set; }
        public string Branch_Name { get; set; }
        public string Branch_IP { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PrincipleName { get; set; }
        public string FileServerDir { get; set; }
    }
}
