//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class WorkflowParameterGetList_Result
    {
        public string WorkFlowCode { get; set; }
        public string WorkFlowTable { get; set; }
        public string WorkFlowTableKey { get; set; }
        public string WorkFlowParameterType { get; set; }
        public string WorkFlowStatusTableKey { get; set; }
        public string WorkFlowStatusDateTableKey { get; set; }
        public string WorkflowViewPage { get; set; }
        public string WorkFlowModule { get; set; }
        public string WorkFlowDescription { get; set; }
        public string Active { get; set; }
    }
}
