//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spRptGAItemAdjustHeader_Result
    {
        public string ItemAdjustId { get; set; }
        public System.DateTime AdjustDate { get; set; }
        public string CreatedName { get; set; }
        public string Warehouse { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string PrintBy { get; set; }
    }
}
