//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spITItemInView_Result
    {
        public string ITItemInCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ReceiveType { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string BranchNameFrom { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedName { get; set; }
        public Nullable<int> ApprovalState { get; set; }
    }
}
