//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spParameterList_List
    {
        public string Parameter_Code { get; set; }
        public string Parameter_Code_Cond { get; set; }
        public string Parameter_Groud_Code { get; set; }
        public string Value { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    }
}
