//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ENTERTAINMENT_GET_DEALER_Result
    {
        public string KODEDEALER { get; set; }
        public string KODEDEALER1 { get; set; }
        public string NAMADEALER { get; set; }
    }
}
