//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class CashRewardPaymentUndefinedGetHeader_Result
    {
        public string PaymentRequestNo { get; set; }
        public string Description { get; set; }
        public string PaymentRequestStatus { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string Active { get; set; }
    }
}
