//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class OpexPaymentEPRReport_Result
    {
        public string OPEX_PAYMENT_NO { get; set; }
        public string BRANCH { get; set; }
        public string DOC_FROM { get; set; }
        public string RECEPIENT_NAME { get; set; }
        public string BENEFICIARY_BANK { get; set; }
        public string RECEPIENT_ACC_NUMBER { get; set; }
        public string RECEPIENT_ACC_NAME { get; set; }
        public string DOCUMENT_TYPE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CCY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> INCLUDE_PPN_AMOUNT { get; set; }
        public Nullable<decimal> FEE_AMOUNT { get; set; }
        public Nullable<decimal> STAMP_DUTY_AMOUNT { get; set; }
        public Nullable<decimal> VAT_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_BIAYA_LAIN { get; set; }
        public Nullable<decimal> WH_TAX_AMOUNT { get; set; }
        public string WH_TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public string RECEPIENT_NPWP { get; set; }
        public string RECEPIENT_ADDRESS { get; set; }
        public string RECEPIENT_ID_NUMBER { get; set; }
    }
}
