//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spITItemOutView_Result
    {
        public string ITItemOutCode { get; set; }
        public string ITItemCode { get; set; }
        public string ITItemName { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemTypeName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string BranchName { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public int ConditionCode { get; set; }
        public string ConditionName { get; set; }
        public int StatusOut { get; set; }
        public string PIC { get; set; }
        public string PICName { get; set; }
        public string Status { get; set; }
        public string RepairStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ApprovalState { get; set; }
        public string CreatedBy { get; set; }
    }
}
