//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class JournalTransactionGet_Result
    {
        public decimal JournalTransactionID { get; set; }
        public string WorkFlowType { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public decimal Debet { get; set; }
        public decimal Credit { get; set; }
        public string TableValue { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Active { get; set; }
        public string Description { get; set; }
        public string BranchCode { get; set; }
        public string SbpCode { get; set; }
        public string FinanceGroup { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
