//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class OpexPaymentCOPPPNGet_Result
    {
        public string TAX_CODE { get; set; }
        public int TRANSACTION_CODE { get; set; }
        public int STATUS_CODE { get; set; }
        public int DOCUMENT_CODE { get; set; }
        public int FLAG_VAT { get; set; }
        public string NPWP { get; set; }
        public string INSURANCE_NAME { get; set; }
        public string NO_FAKTUR_PAJAK { get; set; }
        public int DOCUMENT_TYPE { get; set; }
        public Nullable<System.DateTime> PAID_DATE { get; set; }
        public string TAX_PERIOD_MONTH { get; set; }
        public Nullable<int> TAX_PERIOD_YEAR { get; set; }
        public Nullable<decimal> COMISSION { get; set; }
        public Nullable<decimal> VAT { get; set; }
    }
}
