//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class OpexPaymentGetHeaderUpload_Result
    {
        public string recepient_npwp { get; set; }
        public string recepient_pkp { get; set; }
        public string RECEPIENT_WHTAX { get; set; }
        public double WHTaxValue { get; set; }
        public Nullable<double> VAT { get; set; }
    }
}
