//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ElearningUserResultGet_Result
    {
        public Nullable<long> Number { get; set; }
        public string QuestionerCode { get; set; }
        public decimal ScheduleIdx { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public decimal QuestionerPointTotal { get; set; }
        public System.DateTime TestDate { get; set; }
    }
}
