//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class MsWorkFlowGetViewPage_Result
    {
        public string workflowTableKey { get; set; }
        public string WorkFlowViewPage { get; set; }
        public string WorkFlowTable { get; set; }
        public string WorkFlowTableValue { get; set; }
        public string menuLink { get; set; }
    }
}
