//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spUploadList_Result
    {
        public int UploadId { get; set; }
        public string DirPath { get; set; }
        public string FileExt { get; set; }
        public string FileType { get; set; }
        public Nullable<double> FileSize { get; set; }
    }
}
