//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ENTERTAINMENT_GIFT_INSERT_Result
    {
        public string Nomor { get; set; }
        public int KeyID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
