//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ENTERTAINMENT_GIFT_HISTORY_Result
    {
        public string resId { get; set; }
        public string CreateDate1 { get; set; }
        public Nullable<long> labelNo { get; set; }
        public int KeyID { get; set; }
        public string Branch { get; set; }
        public string ApplName { get; set; }
        public string BankName { get; set; }
        public string AccName { get; set; }
        public string AccNo { get; set; }
        public string AcceptanceOffer { get; set; }
        public string BussinessLine { get; set; }
        public Nullable<int> CountpartyType { get; set; }
        public string CountpartyName { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> EventItems { get; set; }
        public string Place { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Time { get; set; }
        public string OurAtt { get; set; }
        public string CountpartyAtt { get; set; }
        public Nullable<decimal> EstimatedBgt { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string ReasonExceedingBgt { get; set; }
        public string OriReceiptNo { get; set; }
        public string Participant1 { get; set; }
        public string Participant2 { get; set; }
        public string Participant3 { get; set; }
        public Nullable<double> Percentage1 { get; set; }
        public Nullable<double> Percentage2 { get; set; }
        public Nullable<double> Percentage3 { get; set; }
        public Nullable<int> AntiSocialCheck { get; set; }
        public string ReasonAntiSocialCheck { get; set; }
        public string UserName { get; set; }
        public Nullable<int> No { get; set; }
        public int Tahun { get; set; }
        public string Dept { get; set; }
        public string EntertainmentType { get; set; }
        public string Status { get; set; }
        public string CompanyJPN { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> OriReceiptAttach { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    }
}
