//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class CashRewardPaymentGetCount_Result
    {
        public Nullable<int> TOTAL_RECIPIENT { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_TAX { get; set; }
        public Nullable<decimal> TOTAL_NET { get; set; }
    }
}
