//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spRptGAItemRequestDetail_Result
    {
        public Nullable<long> No { get; set; }
        public string ItemRequestDetailId { get; set; }
        public string ItemRequestId { get; set; }
        public int ItemDetailNo { get; set; }
        public double Quantity { get; set; }
        public string Remark { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_by { get; set; }
        public Nullable<int> Maximum { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemTypeName { get; set; }
        public string ItemGroupName { get; set; }
        public string MeasurementCode { get; set; }
    }
}
