//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class CashRewardRequestRecipients_Result
    {
        public string CONTRACT_NUMBER { get; set; }
        public decimal REFUND_RECIPIENT_ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string BRAND_NAME { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public decimal TOTAL_REFUND { get; set; }
        public string REFUND_RECIPIENT_NAME { get; set; }
        public string POSITION { get; set; }
        public decimal AMOUNT { get; set; }
        public decimal TAX_AMOUNT { get; set; }
        public decimal NET_AMOUNT { get; set; }
    }
}
