//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class OpexPaymentFakturGet_Result
    {
        public Nullable<long> Number { get; set; }
        public string OPEX_PAYMENT_NO { get; set; }
        public string RECEPIENT_NAME { get; set; }
        public string RECEPIENT_NPWP { get; set; }
        public string RECEPIENT_ADDRESS { get; set; }
        public Nullable<decimal> COMISSION { get; set; }
        public string FAKTUR_NO { get; set; }
        public Nullable<System.DateTime> FAKTUR_DATE { get; set; }
    }
}
