//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spITItemView_Result
    {
        public string ITItemCode { get; set; }
        public string ITItemInDtlCode { get; set; }
        public string ITItemTransDtlCode { get; set; }
        public string ITItemOutCode { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemTypeName { get; set; }
        public string SerialNo { get; set; }
        public string Barcode { get; set; }
        public string Description { get; set; }
        public int ConditionCode { get; set; }
        public string ConditionName { get; set; }
        public Nullable<int> StatusIn { get; set; }
        public Nullable<int> StatusOut { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string BranchName { get; set; }
        public string UsedBy { get; set; }
        public string PrivilegeCode { get; set; }
        public string PrivilegeName { get; set; }
        public bool IsActive { get; set; }
    }
}
