//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spGetUserLogon_Result
    {
        public string UserId { get; set; }
        public string Pass { get; set; }
        public string UserName { get; set; }
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public string PrivilegeCode { get; set; }
        public string PrivilegeName { get; set; }
        public string DepartementName { get; set; }
        public string Email { get; set; }
        public string EmailB2B { get; set; }
        public string ChangePass { get; set; }
    }
}
