//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ElearningUserTestGet_Result
    {
        public decimal id { get; set; }
        public string UserId { get; set; }
        public string QuestionerCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Update_by { get; set; }
    }
}
