//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spGAItemView_Result
    {
        public int ItemDetailNo { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string DepartementCode { get; set; }
        public string ItemTypeCode { get; set; }
        public double Quantity { get; set; }
        public double RequestQty { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_by { get; set; }
        public bool IsAsset { get; set; }
        public string ItemTypeName { get; set; }
        public string ItemGroupCode { get; set; }
        public string ItemGroupName { get; set; }
        public string ItemCategoryCode { get; set; }
        public string ItemCategoryName { get; set; }
        public string MeasurementCode { get; set; }
        public string BranchName { get; set; }
        public string DepartementName { get; set; }
        public decimal Price { get; set; }
    }
}
