//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spHREmployeeDetailList_Result
    {
        public string JobTypeName { get; set; }
        public string BranchName { get; set; }
        public string DepartementName { get; set; }
        public string PrivilegeName { get; set; }
        public System.DateTime EffectiveDateFrom { get; set; }
        public System.DateTime EffectiveDateTo { get; set; }
        public Nullable<int> JobStatus { get; set; }
        public string JobEmployeeId { get; set; }
    }
}
