//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spRptGAItemStockNonAssetDetail_Result
    {
        public int ItemType_ID { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemTypeName { get; set; }
        public int Branch_ID { get; set; }
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public double StockBegin { get; set; }
        public double StockIn { get; set; }
        public double StockOut { get; set; }
        public double StockOutBranch { get; set; }
        public double StockEnd { get; set; }
        public decimal Price { get; set; }
        public Nullable<double> PriceOut { get; set; }
    }
}
