//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spParameterView_Result
    {
        public string Parameter_Code { get; set; }
        public string Parameter_Code_Cond { get; set; }
        public string Parameter_Group_Code { get; set; }
        public string Parameter_Name { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string update_by { get; set; }
    }
}
