//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class CashRewardGetPricing_Result
    {
        public decimal ID { get; set; }
        public string ASSET_CONDITION { get; set; }
        public string CATEGORY { get; set; }
        public string BRAND_NAME { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public int TENOR { get; set; }
        public string AREA { get; set; }
        public Nullable<decimal> FLAT_RATE { get; set; }
        public Nullable<decimal> ADMIN_FEE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string ACTIVE { get; set; }
    }
}
