//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spGetAssignList_Result
    {
        public System.DateTime DateAssign { get; set; }
        public string StatusActivity { get; set; }
        public string Description { get; set; }
    }
}
