//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spITMailSchedulerList_Result
    {
        public long No { get; set; }
        public System.DateTime StartDate { get; set; }
        public string MailTo { get; set; }
        public string IntervalTime { get; set; }
        public int ScheduleId { get; set; }
    }
}
