//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spMappingApprovalView_Result
    {
        public int ApprovalID { get; set; }
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public string DepartementCode { get; set; }
        public string DepartementName { get; set; }
        public string ParentCode { get; set; }
        public string ParentName { get; set; }
        public string UserIdApproval { get; set; }
        public string UserNameApproval { get; set; }
        public int State { get; set; }
        public Nullable<int> ToState { get; set; }
        public string StateDescription { get; set; }
        public bool IsActive { get; set; }
        public bool IsBranch { get; set; }
    }
}
