//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class MsWorkFlowSourceGetList_Result
    {
        public int BranchId { get; set; }
        public string DepartementCode { get; set; }
        public string WorkFlowType { get; set; }
        public string WorkFlowCode { get; set; }
        public string SpecificValue { get; set; }
        public string Description { get; set; }
        public string Active { get; set; }
        public System.DateTime Created_date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Update_by { get; set; }
    }
}
