//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spGAItemAdjustmentDetailView_Result
    {
        public string ItemAdjustDetailId { get; set; }
        public string ItemAdjustId { get; set; }
        public string ItemCategoryCode { get; set; }
        public string ItemCategoryName { get; set; }
        public string ItemGroupCode { get; set; }
        public string ItemGroupName { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemTypeName { get; set; }
        public double Quantity { get; set; }
        public string Remark { get; set; }
        public string MeasurementCode { get; set; }
        public string MeasurementName { get; set; }
    }
}
