//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ElearningMasterGet_Result
    {
        public Nullable<long> Number { get; set; }
        public string QuestionerCode { get; set; }
        public int BranchId { get; set; }
        public string DepartementCode { get; set; }
        public string QuestionerName { get; set; }
        public string Description { get; set; }
        public string QuestionerLink { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Update_by { get; set; }
    }
}
