//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ADMINFEE_GET_FINANCING_Result
    {
        public string contract_number { get; set; }
        public string name { get; set; }
        public int tenor { get; set; }
        public decimal sellInterest { get; set; }
        public string collateral_number { get; set; }
        public decimal effRate { get; set; }
        public decimal finance_amount { get; set; }
        public decimal OTR { get; set; }
        public decimal admin_fee { get; set; }
        public decimal stdPremi { get; set; }
        public decimal dp_rate { get; set; }
        public decimal inputInt { get; set; }
        public decimal effective_input_rate { get; set; }
        public decimal admPremiCredit { get; set; }
        public decimal other_fee { get; set; }
        public decimal InsuranceRefund { get; set; }
        public decimal refund_portion { get; set; }
        public decimal policy_fee { get; set; }
        public string brand_item_name { get; set; }
        public decimal stdPremiPercent { get; set; }
        public Nullable<decimal> Procentage { get; set; }
        public Nullable<decimal> MaxPercent { get; set; }
        public decimal AdmFee { get; set; }
        public Nullable<System.DateTime> commence_process_date { get; set; }
        public string DealerName { get; set; }
        public decimal policy_fee_Credit { get; set; }
        public Nullable<decimal> tjh { get; set; }
        public string DealerCode { get; set; }
        public string asset_condition_Code { get; set; }
        public Nullable<int> production_year { get; set; }
        public string modelName { get; set; }
        public Nullable<decimal> standard_premium_amount { get; set; }
        public Nullable<decimal> policy_fee_include_to_fa { get; set; }
    }
}
