//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spPrivilegeMenuList_Result
    {
        public string MenuName { get; set; }
        public bool InsertDt { get; set; }
        public string MenuLink { get; set; }
    }
}
