//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ElearningBroadcastDetailGet_Result
    {
        public Nullable<long> Number { get; set; }
        public string QuestionerCode { get; set; }
        public decimal ScheduleIdx { get; set; }
        public string UserType { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string SendConfirmEmail { get; set; }
        public Nullable<System.DateTime> SendConfirmDate { get; set; }
    }
}
