//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spHRDeleteUserRequestList_Result
    {
        public string DeleteRequestId { get; set; }
        public System.DateTime DeleteRequestDate { get; set; }
        public string BranchName { get; set; }
        public string DepartementName { get; set; }
        public string EmployeeName { get; set; }
        public string Status { get; set; }
        public string ProcessStatus { get; set; }
        public string NIK { get; set; }
    }
}
