//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class NomintiveOurAttGetList_Result
    {
        public int NOMINATIVE_NO { get; set; }
        public int NOMINATIVE_IDX { get; set; }
        public string OUR_ATTENDEE_NAME { get; set; }
        public string ACTIVE { get; set; }
        public string CssStyle { get; set; }
    }
}
