//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class OpexPaymentConvertGet_Result
    {
        public decimal ID { get; set; }
        public string BankType { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string AccountNo { get; set; }
        public string Currency { get; set; }
        public string CompanyCode { get; set; }
        public string TransactionRemark { get; set; }
        public string TransactionRemark2 { get; set; }
        public string TransactionType { get; set; }
        public string SectorSelection { get; set; }
        public string BankCharges { get; set; }
    }
}
