//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class ElearningMasterView_Result
    {
        public string QuestionerCode { get; set; }
        public string BranchName { get; set; }
        public string DepartementName { get; set; }
        public string QuestionerName { get; set; }
        public string Description { get; set; }
        public string QuestionerLink { get; set; }
        public bool Active { get; set; }
    }
}
