//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USOFT.DataAccess
{
    using System;
    
    public partial class spGAPurchaseRequestDeliveryDetailView_Result
    {
        public string RequestDetailId { get; set; }
        public string RequestId { get; set; }
        public string ItemCategoryCode { get; set; }
        public string ItemCategoryName { get; set; }
        public string ItemGroupCode { get; set; }
        public string ItemGroupName { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemTypeName { get; set; }
        public double RequestQty { get; set; }
        public double Quantity { get; set; }
        public string MeasurementCode { get; set; }
        public bool IsAsset { get; set; }
        public string Status { get; set; }
    }
}
